version: 2.1

parameters:
  run-build-project-1-job:
    type: boolean
    default: false
  run-build-project-2-job:
    type: boolean
    default: false
  run-build-shared-job:
    type: boolean
    default: false

executors:
  default:
    docker:
      - image: circleci/node:14

jobs:
  build_project1:
    executor: default
    steps:
      - checkout
      - run: echo "Building Project 1"

  build_project2:
    executor: default
    steps:
      - checkout
      - run: echo "Building Project 2"

  build_shared:
    executor: default
    steps:
      - checkout
      - run: echo "Building Shared Dependencies"

workflows:
  project1:
    when: << pipeline.parameters.run-build-project-1-job >>
    jobs:
      - build_project1
  project2:
    when: << pipeline.parameters.run-build-project-2-job >>
    jobs:
      - build_project2
  shared:
    when: << pipeline.parameters.run-build-shared-job >>
    jobs:
      - build_shared
