version: 2.1

parameters:
  project1:
    type: boolean
    default: false
  project2:
    type: boolean
    default: false
  shared:
    type: boolean
    default: false

executors:
  default:
    docker:
      - image: circleci/node:14

workflows:
  service-1:
    when: << pipeline.parameters.run-build-service-1-job >>
    jobs:
      - build_project1:
          name: build_project1
          executor: default
          steps:
            - checkout
            - run: echo "Building Project 1"
  service-2:
    when: << pipeline.parameters.run-build-service-2-job >>
    jobs:
      - build_project1:
          name: build_project2
          executor: default
          steps:
            - checkout
            - run: echo "Building Project 2"
  shared:
    when: << pipeline.parameters.run-build-shared-job >>
    jobs:
      - build_project1:
          name: build_shared
          executor: default
          steps:
            - checkout
            - run: echo "Building Shared Dependencies"
