version: 2.1

parameters:
  project1:
    type: boolean
    default: false
  project2:
    type: boolean
    default: false
  shared:
    type: boolean
    default: false

executors:
  default:
    docker:
      - image: circleci/node:14

jobs:
  build_project1:
    executor: default
    parameters:
      project1:
        type: boolean
    steps:
      - checkout
      - run: echo "Building Project 1"

  build_project2:
    executor: default
    parameters:
      project2:
        type: boolean
    steps:
      - checkout
      - run: echo "Building Project 2"

  build_shared:
    executor: default
    parameters:
      shared:
        type: boolean
    steps:
      - checkout
      - run: echo "Building Shared Dependencies"

workflows:
  version: 2
  project_workflows:
    jobs:
      - build_project1:
          project1: << pipeline.parameters.project1 >>
          when:
            condition: << pipeline.parameters.project1 >>
      - build_project2:
          project2: << pipeline.parameters.project2 >>
          when:
            condition: << pipeline.parameters.project2 >>
      - build_shared:
          shared: << pipeline.parameters.shared >>
          when:
            condition: << pipeline.parameters.shared >>
